//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.FrankaPandaCommunication
{
    [Serializable]
    public class FollowerRequest : Message
    {
        public const string k_RosMessageName = "franka_panda_communication/Follower";
        public override string RosMessageName => k_RosMessageName;

        public PandaMoveitJointsMsg joints_input;
        public PandaMoveitOffsetMsg offset;
        public Geometry.PoseMsg target_pose;

        public FollowerRequest()
        {
            this.joints_input = new PandaMoveitJointsMsg();
            this.offset = new PandaMoveitOffsetMsg();
            this.target_pose = new Geometry.PoseMsg();
        }

        public FollowerRequest(PandaMoveitJointsMsg joints_input, PandaMoveitOffsetMsg offset, Geometry.PoseMsg target_pose)
        {
            this.joints_input = joints_input;
            this.offset = offset;
            this.target_pose = target_pose;
        }

        public static FollowerRequest Deserialize(MessageDeserializer deserializer) => new FollowerRequest(deserializer);

        private FollowerRequest(MessageDeserializer deserializer)
        {
            this.joints_input = PandaMoveitJointsMsg.Deserialize(deserializer);
            this.offset = PandaMoveitOffsetMsg.Deserialize(deserializer);
            this.target_pose = Geometry.PoseMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.joints_input);
            serializer.Write(this.offset);
            serializer.Write(this.target_pose);
        }

        public override string ToString()
        {
            return "FollowerRequest: " +
            "\njoints_input: " + joints_input.ToString() +
            "\noffset: " + offset.ToString() +
            "\ntarget_pose: " + target_pose.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
