//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.FrankaPandaCommunication
{
    [Serializable]
    public class FollowerResponse : Message
    {
        public const string k_RosMessageName = "franka_panda_communication/Follower";
        public override string RosMessageName => k_RosMessageName;

        public Moveit.RobotTrajectoryMsg[] trajectories;

        public FollowerResponse()
        {
            this.trajectories = new Moveit.RobotTrajectoryMsg[0];
        }

        public FollowerResponse(Moveit.RobotTrajectoryMsg[] trajectories)
        {
            this.trajectories = trajectories;
        }

        public static FollowerResponse Deserialize(MessageDeserializer deserializer) => new FollowerResponse(deserializer);

        private FollowerResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.trajectories, Moveit.RobotTrajectoryMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.trajectories);
            serializer.Write(this.trajectories);
        }

        public override string ToString()
        {
            return "FollowerResponse: " +
            "\ntrajectories: " + System.String.Join(", ", trajectories.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
