//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.FrankaPandaCommunication
{
    [Serializable]
    public class GetRobotStateServiceResponse : Message
    {
        public const string k_RosMessageName = "franka_panda_communication/GetRobotStateService";
        public override string RosMessageName => k_RosMessageName;

        public ObjectInfoMsg target;
        public PandaMoveitJointsMsg joints_input;

        public GetRobotStateServiceResponse()
        {
            this.target = new ObjectInfoMsg();
            this.joints_input = new PandaMoveitJointsMsg();
        }

        public GetRobotStateServiceResponse(ObjectInfoMsg target, PandaMoveitJointsMsg joints_input)
        {
            this.target = target;
            this.joints_input = joints_input;
        }

        public static GetRobotStateServiceResponse Deserialize(MessageDeserializer deserializer) => new GetRobotStateServiceResponse(deserializer);

        private GetRobotStateServiceResponse(MessageDeserializer deserializer)
        {
            this.target = ObjectInfoMsg.Deserialize(deserializer);
            this.joints_input = PandaMoveitJointsMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.target);
            serializer.Write(this.joints_input);
        }

        public override string ToString()
        {
            return "GetRobotStateServiceResponse: " +
            "\ntarget: " + target.ToString() +
            "\njoints_input: " + joints_input.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
