//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.FrankaPandaCommunication
{
    [Serializable]
    public class GetRobotStateServiceRequest : Message
    {
        public const string k_RosMessageName = "franka_panda_communication/GetRobotStateService";
        public override string RosMessageName => k_RosMessageName;


        public GetRobotStateServiceRequest()
        {
        }
        public static GetRobotStateServiceRequest Deserialize(MessageDeserializer deserializer) => new GetRobotStateServiceRequest(deserializer);

        private GetRobotStateServiceRequest(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "GetRobotStateServiceRequest: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
