//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.FrankaPandaCommunication
{
    [Serializable]
    public class HandServiceResponse : Message
    {
        public const string k_RosMessageName = "franka_panda_communication/HandService";
        public override string RosMessageName => k_RosMessageName;

        public bool success;

        public HandServiceResponse()
        {
            this.success = false;
        }

        public HandServiceResponse(bool success)
        {
            this.success = success;
        }

        public static HandServiceResponse Deserialize(MessageDeserializer deserializer) => new HandServiceResponse(deserializer);

        private HandServiceResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
        }

        public override string ToString()
        {
            return "HandServiceResponse: " +
            "\nsuccess: " + success.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
