//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.FrankaPandaCommunication
{
    [Serializable]
    public class HandServiceRequest : Message
    {
        public const string k_RosMessageName = "franka_panda_communication/HandService";
        public override string RosMessageName => k_RosMessageName;

        public double[] gripper_targets;

        public HandServiceRequest()
        {
            this.gripper_targets = new double[0];
        }

        public HandServiceRequest(double[] gripper_targets)
        {
            this.gripper_targets = gripper_targets;
        }

        public static HandServiceRequest Deserialize(MessageDeserializer deserializer) => new HandServiceRequest(deserializer);

        private HandServiceRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.gripper_targets, sizeof(double), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.gripper_targets);
            serializer.Write(this.gripper_targets);
        }

        public override string ToString()
        {
            return "HandServiceRequest: " +
            "\ngripper_targets: " + System.String.Join(", ", gripper_targets.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
