//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.FrankaPandaCommunication
{
    [Serializable]
    public class MoveServiceResponse : Message
    {
        public const string k_RosMessageName = "franka_panda_communication/MoveService";
        public override string RosMessageName => k_RosMessageName;

        public bool success;

        public MoveServiceResponse()
        {
            this.success = false;
        }

        public MoveServiceResponse(bool success)
        {
            this.success = success;
        }

        public static MoveServiceResponse Deserialize(MessageDeserializer deserializer) => new MoveServiceResponse(deserializer);

        private MoveServiceResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
        }

        public override string ToString()
        {
            return "MoveServiceResponse: " +
            "\nsuccess: " + success.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
