//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.FrankaPandaCommunication
{
    [Serializable]
    public class MoveServiceRequest : Message
    {
        public const string k_RosMessageName = "franka_panda_communication/MoveService";
        public override string RosMessageName => k_RosMessageName;

        public byte trajectory_type;
        public Moveit.RobotTrajectoryMsg trajectory;

        public MoveServiceRequest()
        {
            this.trajectory_type = 0;
            this.trajectory = new Moveit.RobotTrajectoryMsg();
        }

        public MoveServiceRequest(byte trajectory_type, Moveit.RobotTrajectoryMsg trajectory)
        {
            this.trajectory_type = trajectory_type;
            this.trajectory = trajectory;
        }

        public static MoveServiceRequest Deserialize(MessageDeserializer deserializer) => new MoveServiceRequest(deserializer);

        private MoveServiceRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.trajectory_type);
            this.trajectory = Moveit.RobotTrajectoryMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.trajectory_type);
            serializer.Write(this.trajectory);
        }

        public override string ToString()
        {
            return "MoveServiceRequest: " +
            "\ntrajectory_type: " + trajectory_type.ToString() +
            "\ntrajectory: " + trajectory.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
