//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.FrankaPandaCommunication
{
    [Serializable]
    public class PickAndPlaceRequest : Message
    {
        public const string k_RosMessageName = "franka_panda_communication/PickAndPlace";
        public override string RosMessageName => k_RosMessageName;

        public ObjectInfoMsg target;
        public PandaMoveitJointsMsg joints_input;
        public PandaMoveitOffsetMsg offset;
        public Geometry.PoseMsg pick_pose;
        public Geometry.PoseMsg place_pose;

        public PickAndPlaceRequest()
        {
            this.target = new ObjectInfoMsg();
            this.joints_input = new PandaMoveitJointsMsg();
            this.offset = new PandaMoveitOffsetMsg();
            this.pick_pose = new Geometry.PoseMsg();
            this.place_pose = new Geometry.PoseMsg();
        }

        public PickAndPlaceRequest(ObjectInfoMsg target, PandaMoveitJointsMsg joints_input, PandaMoveitOffsetMsg offset, Geometry.PoseMsg pick_pose, Geometry.PoseMsg place_pose)
        {
            this.target = target;
            this.joints_input = joints_input;
            this.offset = offset;
            this.pick_pose = pick_pose;
            this.place_pose = place_pose;
        }

        public static PickAndPlaceRequest Deserialize(MessageDeserializer deserializer) => new PickAndPlaceRequest(deserializer);

        private PickAndPlaceRequest(MessageDeserializer deserializer)
        {
            this.target = ObjectInfoMsg.Deserialize(deserializer);
            this.joints_input = PandaMoveitJointsMsg.Deserialize(deserializer);
            this.offset = PandaMoveitOffsetMsg.Deserialize(deserializer);
            this.pick_pose = Geometry.PoseMsg.Deserialize(deserializer);
            this.place_pose = Geometry.PoseMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.target);
            serializer.Write(this.joints_input);
            serializer.Write(this.offset);
            serializer.Write(this.pick_pose);
            serializer.Write(this.place_pose);
        }

        public override string ToString()
        {
            return "PickAndPlaceRequest: " +
            "\ntarget: " + target.ToString() +
            "\njoints_input: " + joints_input.ToString() +
            "\noffset: " + offset.ToString() +
            "\npick_pose: " + pick_pose.ToString() +
            "\nplace_pose: " + place_pose.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
