//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.FrankaPandaMoveit
{
    [Serializable]
    public class ObjectInfoMsg : Message
    {
        public const string k_RosMessageName = "franka_panda_moveit/ObjectInfo";
        public override string RosMessageName => k_RosMessageName;

        public string name;
        public Geometry.PointMsg position;
        public Geometry.QuaternionMsg rotation;
        public Geometry.Vector3Msg size;

        public ObjectInfoMsg()
        {
            this.name = "";
            this.position = new Geometry.PointMsg();
            this.rotation = new Geometry.QuaternionMsg();
            this.size = new Geometry.Vector3Msg();
        }

        public ObjectInfoMsg(string name, Geometry.PointMsg position, Geometry.QuaternionMsg rotation, Geometry.Vector3Msg size)
        {
            this.name = name;
            this.position = position;
            this.rotation = rotation;
            this.size = size;
        }

        public static ObjectInfoMsg Deserialize(MessageDeserializer deserializer) => new ObjectInfoMsg(deserializer);

        private ObjectInfoMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.name);
            this.position = Geometry.PointMsg.Deserialize(deserializer);
            this.rotation = Geometry.QuaternionMsg.Deserialize(deserializer);
            this.size = Geometry.Vector3Msg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.name);
            serializer.Write(this.position);
            serializer.Write(this.rotation);
            serializer.Write(this.size);
        }

        public override string ToString()
        {
            return "ObjectInfoMsg: " +
            "\nname: " + name.ToString() +
            "\nposition: " + position.ToString() +
            "\nrotation: " + rotation.ToString() +
            "\nsize: " + size.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
