//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.FrankaPandaMoveit
{
    [Serializable]
    public class PandaMoveitOffsetMsg : Message
    {
        public const string k_RosMessageName = "franka_panda_moveit/PandaMoveitOffset";
        public override string RosMessageName => k_RosMessageName;

        public double offset;

        public PandaMoveitOffsetMsg()
        {
            this.offset = 0.0;
        }

        public PandaMoveitOffsetMsg(double offset)
        {
            this.offset = offset;
        }

        public static PandaMoveitOffsetMsg Deserialize(MessageDeserializer deserializer) => new PandaMoveitOffsetMsg(deserializer);

        private PandaMoveitOffsetMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.offset);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.offset);
        }

        public override string ToString()
        {
            return "PandaMoveitOffsetMsg: " +
            "\noffset: " + offset.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
